name: Package and Upload Release Assets

# Global variables
env:
  PACKAGE_NAME: "security"
  FILES_TO_PACKAGE: "gemini-extension.json BIGQUERY.md LICENSE tools.yaml"
  GCS_BUCKET_URL: "https://storage.googleapis.com/genai-toolbox/geminicli"

on:
  release:
    types: [created]

  # This allows you to run the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag of the release to upload assets to'
        required: true
        type: string

permissions:
  # This permission is required for the action to create a GitHub Release
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version you use
          cache: 'npm'
          # Tell the cache where to find the package-lock.json
          cache-dependency-path: mcp-server/package-lock.json

      # 3. Install MCP server dependencies
      # The MCP server needs its dependencies bundled in the release
      - name: Install MCP server dependencies
        run: cd mcp-server && npm ci

      # 4. Runs your build script
      - name: Run build
        run: cd mcp-server && npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: .

